config/routes.rb
Rails.application.routes.draw do
  resources :leadboards, only: [:index, :show]
  resources :games, only: [:index, :show, :new, :create]
  devise_for :users
  root to: 'games#index'
  get '/history', to: 'home#history'
  get '/log',     to: 'home#log'
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  belongs_to :opponent, class_name: 'User', foreign_key: 'opponent_id'

  validates :user, presence: true
  validates :opponent_id, presence: true
  validates :user_score, presence: true
  validates :opponent_score, presence: true

  validate :validate_minimum_score, :on => :create
  validate :validate_score_difference, :on => :create

  after_create :update_leadboard

  private

  def validate_minimum_score
    # if self.user_score < 11 && self.opponent_score < 11
    #   errors[:base] << 'At least a score should be greater than 11'
    # end

    if self.user_score < 21 && self.opponent_score < 21
      errors[:base] << 'At least a score should be greater than 21'
    end
  end

  def validate_score_difference
    score_difference = (self.user_score - self.opponent_score).abs
    #some_score_is_21 = self.user_score > 20 || self.opponent_score > 20 ? true : false

    # if score_difference < 2 && some_score_is_21 == false
    #   errors[:base] << 'There must be a difference of two points'        
    # end
    if score_difference < 2
      errors[:base] << 'There must be a difference of two points'        
    end

  end

  def update_leadboard
    user_leadboard = self.user.leadboard
    opponent_leadboard = self.opponent.leadboard

    current_user_score = user_leadboard.score
    current_opponent_score = opponent_leadboard.score

    user_leadboard.games += 1
    opponent_leadboard.games += 1

    #When user wins
    if self.user_score > self.opponent_score
      if current_user_score > current_opponent_score
        user_leadboard.score += 1
      else
        user_leadboard.score += 3
      end
    end

    #When opponent wins
    if self.opponent_score > self.user_score
      if current_opponent_score > current_user_score
        opponent_leadboard.score += 1
      else
        opponent_leadboard.score += 3
      end
    end

    user_leadboard.save
    opponent_leadboard.save
  end
end

app/models/leadboard.rb
class Leadboard < ActiveRecord::Base
  belongs_to :user

  validates :user, presence: true
  validates :score, numericality: true
  validates :games, numericality: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :trackable, :validatable

  has_one :leadboard
  has_many :games

  after_create :create_leadboard

  def games
    Game.where('user_id = ? OR opponent_id = ?', self.id, self.id)
  end

  private

  def create_leadboard
    Leadboard.create(user_id: self.id, score: 0, games: 0)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :fetch_opponents, only: [:new, :edit, :create, :update]

  # GET /games
  def index
    @games = Game.where('user_id = ? or opponent_id = ?', current_user.id, current_user.id).order('match_date DESC')
  end

  # GET /games/1
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to @game, notice: 'Game was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /games/1
  def update
    if @game.update(game_params)
      redirect_to @game, notice: 'Game was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /games/1
  def destroy
    @game.destroy
    redirect_to games_url, notice: 'Game was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.where('user_id = ? or opponent_id = ? AND id = ?', current_user.id, current_user.id, params[:id]).first
    end

    # Only allow a trusted parameter "white list" through.
    def game_params
      params.require(:game).permit(:match_date, :user_id, :opponent_id, :user_score, :opponent_score)
    end

    def fetch_opponents
      @user = current_user
      @opponents = User.where.not(id: current_user.id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def history
  end

  def log
  end
end

app/controllers/leadboards_controller.rb
class LeadboardsController < ApplicationController
  before_action :set_leadboard, only: [:show, :edit, :update, :destroy]

  # GET /leadboards
  def index
    @leadboards = Leadboard.order('score DESC')
  end

  # GET /leadboards/1
  def show
  end

  # GET /leadboards/new
  def new
    @leadboard = Leadboard.new
  end

  # GET /leadboards/1/edit
  def edit
  end

  # POST /leadboards
  def create
    @leadboard = Leadboard.new(leadboard_params)

    if @leadboard.save
      redirect_to @leadboard, notice: 'Leadboard was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /leadboards/1
  def update
    if @leadboard.update(leadboard_params)
      redirect_to @leadboard, notice: 'Leadboard was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /leadboards/1
  def destroy
    @leadboard.destroy
    redirect_to leadboards_url, notice: 'Leadboard was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leadboard
      @leadboard = Leadboard.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def leadboard_params
      params.require(:leadboard).permit(:user_id, :score, :games)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/leadboards_helper.rb
module LeadboardsHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :match_date %><br>
    <%= f.date_select :match_date %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="field">
    <%= f.label :opponent_id %><br>
    <%= f.collection_select(:opponent_id, @opponents.all, :id, :email) %>
  </div>
  <div class="field">
    <%= f.label :user_score %><br>
    <%= f.number_field :user_score %>
  </div>
  <div class="field">
    <%= f.label :opponent_score %><br>
    <%= f.number_field :opponent_score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table class="table">
  <thead>
    <tr>
      <th>Match date</th>
      <th>User</th>
      <th>Opponent</th>
      <th>User score</th>
      <th>Opponent score</th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.match_date %></td>
        <td><%= game.user.email %></td>
        <td><%= game.opponent.email %></td>
        <td><%= game.user_score %></td>
        <td><%= game.opponent_score %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path, class: 'btn btn-primary' %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path, class: 'btn btn-secondary' %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Match date:</strong>
  <%= @game.match_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @game.user.email %>
</p>

<p>
  <strong>Opponent:</strong>
  <%= @game.opponent.email %>
</p>

<p>
  <strong>User score:</strong>
  <%= @game.user_score %>
</p>

<p>
  <strong>Opponent score:</strong>
  <%= @game.opponent_score %>
</p>
<%= link_to 'Back', games_path, class: 'btn btn-info' %>

app/views/home/history.html.erb
<h1 class='page-header'>History</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('history.png') %>

app/views/home/index.html.erb
<h1 class='page-header'>Leaderboard</h1>

<div class="alert alert-warning" role="alert">This is a sample page.</div>

<%= image_tag('leaderboard.png') %>

app/views/home/log.html.erb
<h1 class='page-header'>Log Game</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('log_game.png') %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pingpong</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= link_to 'Log Game', new_game_path, class: 'btn btn-success navbar-btn' %>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Leadboard', leadboards_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li> <a href="#">Hi <%= current_user.email %></a></li>
          <li><a href="/games">History</a></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pingpong Leaderboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", integrity: "sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", integrity: "sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>

app/views/leadboards/_form.html.erb
<%= form_for(@leadboard) do |f| %>
  <% if @leadboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leadboard.errors.count, "error") %> prohibited this leadboard from being saved:</h2>

      <ul>
      <% @leadboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :games %><br>
    <%= f.number_field :games %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leadboards/edit.html.erb
<h1>Editing Leadboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @leadboard %> |
<%= link_to 'Back', leadboards_path %>

app/views/leadboards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Leaderboards</h1>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Score</th>
      <th>Games</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @leadboards.each do |leadboard| %>
      <tr>
        <td><%= leadboard.user.email %></td>
        <td><%= leadboard.score %></td>
        <td><%= leadboard.games %></td>
        <td><%= link_to 'Show', leadboard %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/leadboards/new.html.erb
<h1>New Leadboard</h1>

<%= render 'form' %>

<%= link_to 'Back', leadboards_path %>

app/views/leadboards/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <th>User</th>
    <th>Score</th>
    <th>Games</th>
  </thead>
  <tbody>
    <tr>
      <td><%= @leadboard.user.email %></td>
      <td><%= @leadboard.score %></td>
      <td><%= @leadboard.games %></td>
    <tr>
  </tbody>
</table>

<h1>Listing User Games</h1>

<table class="table">
  <thead>
    <tr>
      <th>Match date</th>
      <th>User</th>
      <th>Opponent</th>
      <th>User score</th>
      <th>Opponent score</th>
    </tr>
  </thead>

  <tbody>
    <% @leadboard.user.games.each do |game| %>
      <tr>
        <td><%= game.match_date %></td>
        <td><%= game.user.email %></td>
        <td><%= game.opponent.email %></td>
        <td><%= game.user_score %></td>
        <td><%= game.opponent_score %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', leadboards_path, class: 'btn btn-info' %>